export const REQUIRE_ORDER = "REQUIRE_ORDER";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const REQUIRE_ORDER_BY_ID = "REQUIRE_ORDER_BY_ID";
export const REQUIRE_ORDER_BY_ID_SUCCESS = "REQUIRE_ORDER_BY_ID_SUCCESS";
export const REQUIRE_ORDER_BY_ID_FAIL = "REQUIRE_ORDER_BY_ID_FAIL";