export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST";
export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS";
export const ALL_CATEGORY_FAIL = "ALL_CATEGORY_FAIL";

export const PRICE = "PRICE";
export const PRICE_ERROR = "PRICE_ERROR";

export const RATINGS = "RATINGS";
export const RATINGS_ERROR = "RATINGS_ERROR";

export const CATEGORY = "CATGORY";
export const CATEGORY_ERROR = "CATGORY_ERROR";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const REMOVE_ITEM = "REMOVE_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";

export const ALL_PRODUCT_DETAIL_REQUEST = "ALL_PRODUCT_DETAIL_REQUEST";
export const ALL_PRODUCT_DETAIL_SUCCESS = "ALL_PRODUCT_DETAIL_SUCCESS";
export const ALL_PRODUCT_DETAIL_FAIL = "ALL_PRODUCT_DETAIL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";