export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REQUIRE_LOGIN = "REQUIRE_LOGIN";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const REQUIRE_LOGOUT = "REQUIRE_LOGOUT";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const REQUIRE_SIGNIN = "REQUIRE_SIGNIN";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
export const REQUIRE_LOAD_USER = "REQUIRE_LOAD_USER";

export const REQUIRE_UPDATE_PROFILE = "REQUIRE_UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const REQUIRE_UPDATE_PASSWORD = "REQUIRE_UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const REQUIRE_FORGOT_PASSWORD = "REQUIRE_FORGOT_PASSWORD";
export const MAIL_SENT_SUCCESS = "MAIL_SENT_SUCCESS";
export const MAIL_SENT_FAIL = "MAIL_SENT_FAIL"

export const REQUIRE_RESET_PASSWORD = "REQUIRE_RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";